### ISSUE TITLE
RSS feed support ?

### ISSUE THREAD

**Issue by v9ai** [wuz/wuz.fyi#1]
Hello, it would be nice to be able to follow this site via RSS:
https://www.gatsbyjs.org/docs/adding-an-rss-feed/

**Comment by wuz** [comment]
Hey! There is one! I should definitely add a link though!

[RSS Feed](https://wuz.fyi/feed.xml)

**Comment by v9ai** [comment]
The news reader I am using is not automatically looking for `feed.xml`.
![image](https://user-images.githubusercontent.com/1477453/57939496-283c8c00-78d3-11e9-835d-9b818f9d8539.png)

Supplying direct link is working, thx:
![image](https://user-images.githubusercontent.com/1477453/57939548-3e4a4c80-78d3-11e9-9b87-12fdc55699cd.png)

**Comment by wuz** [comment]
Great! I also added a link to the footer! Thanks for the suggestion :)
